//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Projesi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SatisyapEntities : DbContext
    {
        public SatisyapEntities()
            : base("name=SatisyapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_kategori> tbl_kategori { get; set; }
        public virtual DbSet<tbl_musteri> tbl_musteri { get; set; }
        public virtual DbSet<tbl_satis> tbl_satis { get; set; }
        public virtual DbSet<tbl_urun> tbl_urun { get; set; }
    
        public virtual ObjectResult<string> Urungetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Urungetir");
        }
    }
}
